<?php

namespace AppBundle\Repository;

/**
 * PerfumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfumRepository extends \Doctrine\ORM\EntityRepository
{
}
